### ISSUE TITLE
Assertion failure in reset_freetype_face_char_size

### ISSUE THREAD

**Issue by yshui** [servo/font-kit#133]
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `23`,
 right: `0`', /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/loaders/freety
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.r
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1428
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:332
  13: font_kit::loaders::freetype::reset_freetype_face_char_size
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/loaders/free
  14: font_kit::loaders::freetype::setup_freetype_face
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/loaders/free
  15: font_kit::loaders::freetype::Font::from_bytes::{{closure}}
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/loaders/free
  16: std::thread::local::LocalKey<T>::try_with
             at /rustc/442ae7f04026c215a03b155eaaf9cde8bb5cf02a/src/libstd/thread/local.rs:262
  17: std::thread::local::LocalKey<T>::with
             at /rustc/442ae7f04026c215a03b155eaaf9cde8bb5cf02a/src/libstd/thread/local.rs:239
  18: font_kit::loaders::freetype::Font::from_bytes
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/loaders/free
  19: font_kit::loaders::freetype::Font::from_file
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/loaders/free
  20: <font_kit::loaders::freetype::Font as font_kit::loader::Loader>::from_file
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/loaders/free
  21: font_kit::loader::Loader::from_path
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/loader.rs:90
  22: font_kit::loader::Loader::from_handle
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/loader.rs:10
  23: font_kit::loaders::freetype::Font::from_handle
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/loaders/free
  24: font_kit::source::Source::select_descriptions_in_family
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/source.rs:14
  25: font_kit::source::Source::select_best_match
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/source.rs:13
  26: font_kit::sources::fontconfig::FontconfigSource::select_best_match
             at /home/shui/.cargo/registry/src/github.com-1ecc6299db9ec823/font-kit-0.5.0/src/sources/font
 ```

**Comment by samyak-jain** [comment]
@yshui I'm facing the same issue. Did you figure out what was causing it?
