### ISSUE TITLE
Rasterization of whitespace glyph causes panic

### ISSUE THREAD

**Issue by ApoorvaJ** [servo/font-kit#7]
Might be Windows-specific.

Minimal repro:

```
let font = SystemSource::new().select_by_postscript_name("ArialMT")
                              .unwrap()
                              .load()
                              .unwrap();
let glyph_id = font.glyph_for_char(' ').unwrap();
font.rasterize_glyph(
    &mut canvas,
    glyph_id,
    font_size,
    &Point2D::zero(),
    HintingOptions::Vertical(font_size),
    RasterizationOptions::GrayscaleAa
); // <--- Panic

```
Here's the backtrace:

```
thread 'main' panicked at 'assertion failed: hr == 0', C:\Users\foobar\.cargo\registry\src\github.com-1ecc6299db9ec823\dwrote-0.5.1\src\glyph_run_analysis.rs:72:13
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   4: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   5: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:475
   7: std::panicking::begin_panic<str*>
             at C:\projects\rust\src\libstd\panicking.rs:409
   8: dwrote::glyph_run_analysis::GlyphRunAnalysis::create_alpha_texture
             at C:\Users\foobar\.cargo\registry\src\github.com-1ecc6299db9ec823\dwrote-0.5.1\src\glyph_run_analysis.rs:72
   9: font_kit::loaders::directwrite::Font::rasterize_glyph
             at C:\Users\foobar\.cargo\registry\src\github.com-1ecc6299db9ec823\font-kit-0.1.0\src\loaders\directwrite.rs:399
  10: foobar::main
             at .\src\main.rs:288
  11: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  12: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  13: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  14: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  15: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  16: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  17: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  18: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  19: main
  20: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:74
  21: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:74
  22: BaseThreadInitThunk
  23: RtlUserThreadStart
error: process didn't exit successfully: `target\debug\foobar.exe` (exit code: 101)
```

**Comment by ApoorvaJ** [comment]
Yes. I'm currently checking for a zeroed rect and earlying out. However, a panic still isn't the best way to go, API-wise.

**Comment by pcwalton** [comment]
> Is there any reason `rasterize_glyph` isn't just a no-op on whitespace glyphs? I feel like that's the nicest API design personally.

No good reason. I agree that's what it should do.

**Comment by jneem** [comment]
The panic doesn't happen for me on linux using fontconfig.

**Comment by Aloxaf** [comment]
This happens on macOS too (https://github.com/Aloxaf/silicon/issues/7)

If this won't be fixed, I think the document should remind users not to rasterize whitespace character

<details>
 <summary>Backtrace</summary>

```
thread 'main' panicked at 'assertion failed: !result.is_null()', /Users/aloxaf/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/core-graphics-0.17.3/src/context.rs:104:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: core::ptr::swap_nonoverlapping_bytes
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/panicking.rs:408
   6: alloc::alloc::dealloc
             at /Users/aloxaf/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/core-graphics-0.17.3/src/context.rs:104
   7: font_kit::loaders::core_text::Font::full_name
             at /Users/aloxaf/.cargo/git/checkouts/font-kit-d9806b026cba48b6/2fd68a8/src/loaders/core_text.rs:521
   8: silicon::font::PositionedGlyph::draw
             at src/font.rs:286
   9: silicon::font::FontCollection::draw_text_mut
             at src/font.rs:253
  10: silicon::formatter::ImageFormatter::draw_line_number
             at src/formatter.rs:183
  11: silicon::formatter::ImageFormatter::format
             at src/formatter.rs:236
  12: silicon::run
             at src/main.rs:46
  13: silicon::main
             at src/main.rs:72
  14: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  15: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  16: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  17: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  18: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  19: silicon::main
```

</details>

**Comment by jdm** [comment]
The stack trace shows a different panic happening onmacOS than Windows, interestingly.
